iw: Add linux-libc-headers expliciet to DEPENDS to fix build cube
Exception: FileExistsError: [Errno 17] File exists: '/home/hains/openpli-oe-core/build/tmp/sysroots-components/cube/libnl/usr/include/linux/nl80211.h' ->
 '/home/hains/openpli-oe-core/build/tmp/work/armv7a-vfp-oe-linux-gnueabi/iw/4.9-r0/recipe-sysroot/usr/include/linux/nl80211.h'

Also libnl, because addition assignment doesn't work.